### ISSUE TITLE
Implement photo gallery for WIL offering

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite-new#1]
Implement photo gallery for WIL as shown in the [prototype](https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=729%3A2341&scaling=scale-down-width&page-id=685%3A202&starting-point-node-id=729%3A2063)

Photos can be found at https://drive.google.com/drive/folders/1Q6ImdpS4OfPMof2DNjn1-GQulbM1IWui

**Comment by jfredrickson5** [comment]
@actuallyjenn I can't find the first image with two people sitting in the chairs, but was able to download the other two.

**Comment by actuallyjenn** [comment]
@jfredrickson5 what's in the prototype is actually a placeholder and we were hoping to have the 24 photos in the link be part of the photo gallery. i was thinking that these would be thumb nails on the page and folks could click on them to open them larger in a light box (i think that's the word for it...)

**Comment by actuallyjenn** [comment]
this looks great @jfredrickson5. thanks!!
