### ISSUE TITLE
No photos on emerging offerings

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#14]
The photos from the [prototype for emerging offerings](https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=685%3A331&scaling=scale-down-width&page-id=685%3A202&starting-point-node-id=729%3A2063) are not included in the [website](https://workplace.gsa.gov/offerings/)

**Comment by vickimcfadden** [comment]
Fast track space: image is a little boring, maybe let's sub for this one: https://drive.google.com/file/d/1s6s-Hc1DKMg9YwT9oMyq-KE17n8j9YTT/view?usp=sharing
Federal coworking: (still looking)
Federal Space Listing: this is a stock photo and I'm not sure if GSA has rights to it, so maybe let's use a screengrab of the ilop tool? 

![Screen Shot 2023-01-23 at 10 35 35 AM](https://user-images.githubusercontent.com/23263170/214081054-69e911f3-4614-4fbb-8e0c-dd37ab7ad8fc.png)

**Comment by JessicaMarine1** [comment]
Does this photo work for the Federal Space Listing one? https://docs.google.com/presentation/d/1jeGGpks3MeFtSZwdUhFuTf4GnzxqTC-uydclNO2CqMk/edit#slide=id.g1c29951a6b1_0_708

**Comment by jfredrickson5** [comment]
Have we nailed down the photos for this one?

**Comment by JessicaMarine1** [comment]
Let's try:
Fast track space: image is a little boring, maybe let's sub for this one: https://drive.google.com/file/d/1s6s-Hc1DKMg9YwT9oMyq-KE17n8j9YTT/view?usp=sharing
Federal coworking: [(here)](https://drive.google.com/file/d/1NE--JP_2ulf8FbmsQnTJDf5IioO0Zxem/view?usp=sharing)
Federal Space Listing: https://docs.google.com/presentation/d/1jeGGpks3MeFtSZwdUhFuTf4GnzxqTC-uydclNO2CqMk/edit#slide=id.g1c29951a6b1_0_708
