### ISSUE TITLE
Spacing on Insights page

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#16]
On the [Insights page](https://workplace.gsa.gov/insights/), need more padding between the two rows of articles.

**Prototype:**
<img width="1060" alt="Screen Shot 2023-01-21 at 8 05 42 PM" src="https://user-images.githubusercontent.com/92383362/213895960-c2d8597c-59b0-4777-a8a9-0c5e3c93e32f.png">

**As implemented:**
![Screen Shot 2023-01-21 at 8 04 39 PM](https://user-images.githubusercontent.com/92383362/213895938-1715ecaa-6d7e-462d-a326-372ae72e0baa.png)

**Comment by weiwang-gsa** [comment]
code fix is checked in content-update branch, it can be verified once the code is merged to main and new build is up.
