### ISSUE TITLE
About page: Extra blank lines

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#18]
Double check the spacing on the [About](https://workplace.gsa.gov/about/) page.

**Prototype:**
<img width="839" alt="Screen Shot 2023-01-21 at 8 09 59 PM" src="https://user-images.githubusercontent.com/92383362/213896060-196d6d47-a3ac-48c1-9653-1031a1ba7cc7.png">

**As Implemented:**
![Screen Shot 2023-01-21 at 8 10 28 PM](https://user-images.githubusercontent.com/92383362/213896073-ce0319f6-db97-42d4-b50e-4032ca4548f8.png)

**Comment by weiwang-gsa** [comment]
code fix is checked in content-update branch, it can be verified once the code is merged to main and new build is up.
