### ISSUE TITLE
Contact page: referring folks to OSC

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#19]
**As implemented:**
For all media or speaker inquiries, please email GSA's [Office of Strategic Communication (OSC)](https://www.gsa.gov/about-us/organization/office-of-strategic-communication).

**Please change to:**
For all media or speaker inquiries, please email GSA’s [Office of Strategic Communication](https://www.gsa.gov/about-us/organization/office-of-strategic-communication) at [press@gsa.gov](mailto:press@gsa.gov).

**Comment by vickimcfadden** [comment]
For all media or speaker inquiries, please email GSA’s [Office of Strategic Communication](https://www.gsa.gov/about-us/organization/office-of-strategic-communication) at press@gsa.gov.
