### ISSUE TITLE
NCR article: missing content

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#24]
The [NCR article](https://workplace.gsa.gov/insights/nrc-gsa-space-reduction-and-cost-savings-in-new-lease/) doesn't have any content loaded. It just references the user to where is was previously published.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 @vickimcfadden I actually asked question last Friday, it is kinda wired only display one sentence in a post ( content is from content tracker). I asked if it should goes to NCR article directly instead of going to an individual post with only one sentence links to NCR article. Please let me know your decision.

**Comment by weiwang-gsa** [comment]
> The product owner wants the content pulled into our site while maintaining the reference / link to the original source. This should look similar to the USAID article.
> 
> You can find the original content at: https://www.gsa.gov/about-us/regions/welcome-to-the-midatlantic-region-3/region-3-newsroom/midatlantic-region-focus-newsletter/nrc-praises-space-reduction-and-cost-savings-in-new-lease?utm_medium=email&utm_source=govDelivery

Thanks for clarification, now I get it, let me working on the fix, will send you screen shot for verification before I check in the code

**Comment by JessicaMarine1** [comment]
Also, if any of the images are still blurry, OSC just provided us some more originals for this article:
https://drive.google.com/file/d/15q0LQ8MOMhcKduee2b0LWCjhT-ppmZro/view?usp=sharing, https://drive.google.com/file/d/1DQ6jP-lyz2phVFtISREt93Dtl-aFe5bT/view?usp=sharing, https://drive.google.com/file/d/1U0S5wgWc7dozLV8BCIqwdm74f9iVLeYe/view?usp=sharing

**Comment by weiwang-gsa** [comment]
> https://drive.google.com/file/d/15q0LQ8MOMhcKduee2b0LWCjhT-ppmZro/view?usp=sharing

awesome! I was waiting for NRC original image, thank you!

**Comment by weiwang-gsa** [comment]
code fix is checked in content-update branch, it can be verified once the code is merged to main and new build is up.
