### ISSUE TITLE
Insights | USAID + GSA | content tweaks

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#31]
(content is squeezed to the left, similar to the other Articles)

USAID + GSA : Consolidating space to drive cost avoidance
January 23, 2023
`is it possible to add a secondary header?` `‘Two-headquarter solution’ comes into focus for U.S. Agency for International Development`

A decade ago, the U.S. Agency for International Development’s 4,000 headquarters personnel were spread across seven Washington, DC, and Virginia locations in `remove duplicative in` leased office spaces, , one of which was a warehouse `remove parentheses`

“The unrenovated parts of our offices looked just like they did in 1995,” said Tony Bennett, chief of the Headquarters Management Division at USAID, during this [summer’s 2022 PBS Customer Forum](https://www.gsa.gov/about-us/organization/public-buildings-service/office-of-portfolio-mgmt-customer-engagement/office-of-customer-engagement/pbs-customer-forums) `add URL`.

Additionally, GSA maintained strong lines of communication with USAID as its strategy moved forward. “In the early phases of the project, our goal was to develop a solution-based, proactive culture across all stakeholders,” said Nadiyah Scarlett, capital projects division director of a regional Design and Construction Division, and one of several GSA workplace personnel who managed USAID’s `remove duplicative apostrophe` consolidation. 

This collaboration, Scarlett explained, facilitated decision- `remove extra space between decision and making`making and kept the project on track.

This article was originally published in the October 2022 [Workscape newsletter] `update URL to 
 (https://content.govdelivery.com/accounts/USGSA/bulletins/330e523)`

**Comment by vickimcfadden** [comment]
Still working on this one, not ready to be pulled over to backlog.

**Comment by JessicaMarine1** [comment]
Added updated URL; moving to ready

**Comment by weiwang-gsa** [comment]
code checked in except for " is it possible to add a secondary header? ‘Two-headquarter solution’ comes into focus for U.S. Agency for International Development", clarification needed what this text needs to go.

**Comment by vickimcfadden** [comment]
If there is a way to add a sub-title above the picture, please include the secondary header. If that looks weird or is clunky. Just delete. I don't think it adds a lot tbh.

**Comment by weiwang-gsa** [comment]
checked in the code fix, it is in build now. somehow customized class for subtible h2 not working, it will get over-writen by h2 style. used inline-style for this.

**Comment by actuallyjenn** [comment]
thanks! looks great
