### ISSUE TITLE
Insights | NRC + GSA | content tweaks

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/wp2030-microsite-new#34]
(content squeezed to the left, as in all articles)

NRC Region `add a as in Regional Administrator` I Administrator David Lew

**Comment by brentryanjohnson** [comment]
I'm a little confused about this one...how should the final sentence read @vickimcfadden?

**Comment by vickimcfadden** [comment]
My bad, we can delete this content tweak @brentryanjohnson . It looks like NRC does have something called Region I

https://www.nrc.gov/docs/ML1822/ML18226A152.pdf
