### ISSUE TITLE
Offerings | WIFM | content tweaks

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/wp2030-microsite-new#37]
Discover opportunities for space efficiency through hybrid work `title, not a bullet`

After title, add customer quote (new): `“The training that [GSA] provided was wonderful. GSA’s engagement with this [WIFM] tool has been outstanding and I have appreciated it. A true example of customer service.” 
— Elizabeth Olexa, U.S. Department of Agriculture`

contact email looks lonely compared to other offerings
`add .. To learn more about the WIFM, email workplace@gsa.gov.`

**Comment by brentryanjohnson** [comment]
@vickimcfadden After which title?

> After title, add customer quote (new)...

**Comment by brentryanjohnson** [comment]
Never mind! Found it.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson I think you missed this last bit:

contact email looks lonely compared to other offerings
add .. To learn more about the WIFM, email workplace@gsa.gov.

**Comment by brentryanjohnson** [comment]
Thanks @JessicaMarine1! On it!
