### ISSUE TITLE
Insights | Return to office best practices | content revisions

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/wp2030-microsite-new#41]
Replace current title and content with: https://docs.google.com/document/d/17L9pnvcOGdeq_Wu02qBzGCqyjWbSDBn6NW6FmrmMIso/edit#heading=h.jkckadel1i4h

**Comment by JessicaMarine1** [comment]
This was a heavy re-write so I'm not sure a compare doc is even helpful, but here it is: https://docs.google.com/document/d/1OI0dQrXcKBhzinmJXBFLtN-hpvxqLrzCQgeFg1iFTj4/edit

**Comment by actuallyjenn** [comment]
thanks! i'm just going to replace the full text with the updates.

**Comment by vickimcfadden** [comment]
As a blogging best practice, let's bold the sentence after the numbers:
- Establish a clear rationale and expectations for returning to office. 
- Help managers establish new norms.
(etc)

**Comment by JessicaMarine1** [comment]
@actuallyjenn there was some back and forth on whether the title should be `Return to Office Strategies` or `Return to Office strategies`. Leslie doesn't care lol

**Comment by actuallyjenn** [comment]
@jfredrickson5 @weiwang-gsa in the content, it looks like they want a mixed list with numbers and letters but i couldn't figure out how to do that so feel free to update. 

1. item
2. item
  a. sub item
  b. sub item
3. item

**Comment by JessicaMarine1** [comment]
The PO believes that Return to Work and Future of Work should be capitalized across the site. Because they generally have not been for MVP, she approved using sentence case for the title of this article for MVP and she will review the site's content post-MVP for any capitalization changes needed.
