### ISSUE TITLE
Offerings headings are not in sequentially descending order

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/wp2030-microsite-new#46]
Heading level jumps from `h1` to `h3` on Offerings page. For accessibility reasons, we shouldn't skip from `h1` to `h3`.

- 1 OFFERINGS
  - 3 Align your workplace and workforce
  - 3 Visit the Workplace Innovation Lab
  - 3 Cowork in commercial space
  - 3 Model your workplace using our tool
- 1 Wondering about the latest workplace trends and analysis?
  - 2 Emerging Offerings
    - 3 Fast track space
    - 3 Federal coworking
    - 3 Federal space listing
  - 2 Participate in our community
    - 3 Subscribe to our newsletter
    - 3 Attend an upcoming event

**Comment by actuallyjenn** [comment]
i'm fine to make the offering headings `h2`. i would do this myself but i don't have a local build, feel free to make that update!
