### ISSUE TITLE
Accessibility error on homepage insights links

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/wp2030-microsite-new#47]
- Lighthouse throws an accessibility error for links not having discernible names
  - Images wrapped in anchors

**Comment by weiwang-gsa** [comment]
@actuallyjenn can we remove the link from the image, leave only the title underneath the image linked to individual insight post?

**Comment by weiwang-gsa** [comment]
added aira-label for the image link, code change checked into branch. It can be re-tested once in build.

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 Looks like @mark-meyer approved ✅

**Comment by brentryanjohnson** [comment]
Reopening because the homepage has the same error. Opened a [PR for review](https://github.com/GSA/wp2030-microsite/pull/66).

**Comment by JessicaMarine1** [comment]
@brentryanjohnson Can you confirm the second item is now fixed?

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 Yes! Both pages are clearing accessibility checks now :)
