### ISSUE TITLE
Updates to insight page layout + fonts

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#49]
@actuallyjenn Can you take a look at the headings that appear throughout these articles and determine what should be done re: sizing. They seem bigger than the title of the article itself.

- [ ] https://workplace.gsa.gov/insights/interesting-times-produce-creative-opportunities/
   - [ ] 10 percent technology, 90 percent sociology
   - [ ] Workplace is about bringing together the right people for the right conversation
- [ ] https://workplace.gsa.gov/insights/usaid-gsa-consolidating-space-to-drive-cost-avoidance/
   - [ ] Seven disparate spaces in one metro area
   - [ ] GSA as a ‘model for change’
   - [ ] Pilot project spurs additional renovation

There is also an issue with how far across the page the text should be wrapping.

**Comment by weiwang-gsa** [comment]
please check wp2030 channel screen shot of changes I plan to implement, and let me know if it will be better if I made the change.

**Comment by actuallyjenn** [comment]
**Font sizes:** I think we should have this be consistent across the site. I don't know how difficult it is to implement the [USWDS theme tokens for typography](https://designsystem.digital.gov/design-tokens/typesetting/font-size/) but I'd rather standardize and go that route. Body font on the homepage, etc and on the insight articles are different. My recommendation:

For offerings and insight pages:
Prose>H1 - '2xl' token (40px or 2.5rem)
Prose>H2 - 'xl' token (32px or 2rem)

Across entire site:
Body - 'md' token (17px or 1.0625rem)

**Text wrapping:** For this, it seems like the `headings` are getting the full-width (960px) while `<p> text` have a smaller width (68ex). For the insight pages, we had a [different layout](https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=744%3A2497&scaling=min-zoom&page-id=685%3A202&starting-point-node-id=729%3A2063) where the margins are larger, a smaller width, and centered on the page. I'm fine with using 68ex as the content width. If it helps, I modeled the insight pages off of how [18F blogs](https://18f.gsa.gov/2022/11/14/improving-inclusion-continuously-how-we-iterated-on-our-bot-to-promote-more-inclusive-and-thoughtful-language/) are structured.

**Comment by JessicaMarine1** [comment]
@weiwang-gsa please see Jenn's comments above

**Comment by JessicaMarine1** [comment]
@actuallyjenn do you want to review this to see if the changes have been implemented as you intended?

**Comment by actuallyjenn** [comment]
yep! this looks good. we decided to go with 1.8rem for sub headings instead to help differentiate between headings.

**Comment by actuallyjenn** [comment]
text wrapping has also been fixed!
