### ISSUE TITLE
Content changes needed for Customer Collaboration Article on Insights page

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#5]
https://workplace.gsa.gov/workplace/insights/gsas-customer-collaboration-event-recap/

- [x] Remove the title "GSA’s Workplace 2030 customer event looks at industry trends and space solutions" from under the picture
- [x] About 2/3 of the way down the page, there is some bold text that starts: **Workplace 2030 customer event looks at industry trends and space solutions**...; please delete all the content from there to the end of the article -- that is a separate article that was inadvertently included in the content

**Comment by weiwang-gsa** [comment]
code fix is checked into content-update branch. Once the code is merge into main branch and build is pushed, you should be able to verify the fix

**Comment by JessicaMarine1** [comment]
Changes look good to me!
