### ISSUE TITLE
Homepage hero subtext wrapping

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite-new#57]
Hero subtext is wrapping but it shouldn't. 

![Image](https://user-images.githubusercontent.com/6501138/214358312-ba11d663-9638-48a1-8927-aec275f1f8ba.png)

**Comment by actuallyjenn** [comment]
thanks @mark-meyer! it looks great, but now it's not centered since there's an extra margin below the paragraph - lol. i would normally go in to make the css change myself but i don't have it built locally so i'm just making simple content changes where i can. do you mind making the update?

**current:**
![Image](https://user-images.githubusercontent.com/6501138/214434185-5160552f-3a54-40d2-9770-6a5b9002b29f.png)


**updated:**
![Image](https://user-images.githubusercontent.com/6501138/214434133-9ac0ec21-c7a0-4885-aaf2-a682110bb622.png)

**Comment by mark-meyer** [comment]
Got it...there's a pr removing that bottom margin.
