### ISSUE TITLE
Fix margin for Insights section on homepage in mobile

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite-new#58]
The insights section on the homepage on mobile should match the layout for the insights page:

**Insights section on homepage:**
![Image](https://user-images.githubusercontent.com/6501138/214368781-18c02fa0-b54b-40ad-9963-ea8c306fd65d.png)
Would it also be possible to put the button below the 3 insight posts when in mobile view?

**Insights section on Insights page:**
![Image](https://user-images.githubusercontent.com/6501138/214368853-96b2ebdc-b109-4918-acb3-b1ee2fb11256.png)

**Comment by mark-meyer** [comment]
@actuallyjenn maybe someone will jump in and correct me, but I think the reordering of the button relative to the posts will be tricky. The margins are a simple fix. I wonder if we could make a backlog issue about the button and push the fix for margins through.

**Comment by jfredrickson5** [comment]
I think we could have two buttons, and show/hide them based on responsive breakpoints.

**Comment by actuallyjenn** [comment]
thanks! this looks great.
