### ISSUE TITLE
Ensure photos have alt text

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/wp2030-microsite-new#6]
Hero/feature photos likely do not need alt text, since they are decorative.

Photos that are displayed alongside content (i.e., that are used to help illustrate the content) must have alt text.

**Comment by weiwang-gsa** [comment]
@mark-meyer I noticed you've already have fix checked in for this in one of pull request, so I put you as "Assignee" and move this ticket to "in progress"

**Comment by brentryanjohnson** [comment]
See #43

**Comment by brentryanjohnson** [comment]
Done ✅
