### ISSUE TITLE
Increase line height for readability

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite-new#63]
Right now the site has the line height at `1.15`. Can we increase it a notch to `1.3`? I'm not sure where the css change otherwise I would do it myself. :) 

**current:**
![Image](https://user-images.githubusercontent.com/6501138/214438815-cf2364b9-bbf1-44a0-8686-19869f03f836.png)

**updated:**
![Image](https://user-images.githubusercontent.com/6501138/214438913-7d945954-bf02-484a-9160-ea193e8d0b62.png)

**Comment by weiwang-gsa** [comment]
@actuallyjenn  is it only for home page guiding principles section, or you want a global change for all pages except for offerings and insights individual posts? I know offerings and insights individual posts ( not the parent page) are having line-height of 1.5 per class "usa-prose". Other pages line height is default from USWDS

**Comment by actuallyjenn** [comment]
looks great, thanks @weiwang-gsa!
