### ISSUE TITLE
Extra space in By line in Insight articles

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite-new#8]
There is an extra space between the author's name and the comma in some of the Insight articles:
- [x] https://workplace.gsa.gov/insights/return-to-office-best-practice/
- [x] https://workplace.gsa.gov/insights/interesting-times-produce-creative-opportunities/

**Comment by weiwang-gsa** [comment]
code fix checked in content-update branch. It can be verified once it is pushed to build.
